#--------------------------------------------------------------------------------------------------
# Configuration script for use with continuous integration service travis-ci.org
#

sudo: required
dist: trusty

language: cpp
compiler:
    - gcc
    - clang
os:
    - linux
    - osx

env:
    matrix:
        - STD="CPP11" BUILD_TYPE="None"
        - STD="CPP11" BUILD_TYPE="Debug"
        - STD="CPP11" BUILD_TYPE="RelWithDebInfo"
        - STD="CPP11" BUILD_TYPE="Release"
        - STD="CPP11" BUILD_TYPE="MinSizeRel"
        - STD="CPP14" BUILD_TYPE="None"
        - STD="CPP14" BUILD_TYPE="Debug"
        - STD="CPP14" BUILD_TYPE="RelWithDebInfo"
        - STD="CPP14" BUILD_TYPE="Release"
        - STD="CPP14" BUILD_TYPE="MinSizeRel"

addons:
    apt: 
        sources:
            - boost-latest
            - ubuntu-toolchain-r-test
        packages:
            - libboost1.55-all-dev
            - libglew-dev
            - libxi-dev
            - libxmu-dev
            - freeglut3-dev


before_install:
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then travis_retry brew install glew ;fi
script:

    - export COMPILER_FLAGS="-msse4.1"
    - if [ "$STD" = "CPP11" ]; then export COMPILER_FLAGS="${COMPILER_FLAGS} -std=c++11"; fi
    - if [ "$STD" = "CPP14" ]; then export COMPILER_FLAGS="${COMPILER_FLAGS} -std=c++1y"; fi
    - echo ${COMPILER_FLAGS}

    - mkdir -p build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=${BUILD_TYPE} "-DCMAKE_CXX_FLAGS=${COMPILER_FLAGS}" -DVSNRAY_ENABLE_EXAMPLES=ON
    - make VERBOSE=1
    - ctest -E 'unittests|surface_.*_illegal_integral_2|vector._pack_illegal_integral|vector._unpack_illegal_integral'
    - sudo make install
