language: cpp
compiler:
    - gcc
    - clang
before_install:
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get update -qq
    - sudo apt-get install -qq g++-4.8 cmake libxi-dev libxmu-dev freeglut3-dev
    - wget http://launchpadlibrarian.net/161405671/libglew1.10_1.10.0-3_amd64.deb
    - wget http://launchpadlibrarian.net/161405670/libglew-dev_1.10.0-3_amd64.deb
    - wget http://launchpadlibrarian.net/160798967/libboost1.54-dev_1.54.0-4ubuntu3_amd64.deb
    - sudo dpkg -i libglew1.10_1.10.0-3_amd64.deb
    - sudo dpkg -i libglew-dev_1.10.0-3_amd64.deb
    - sudo dpkg -i libboost1.54-dev_1.54.0-4ubuntu3_amd64.deb
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
script:
    - printf "set(GLEW_INCLUDE_DIR \"/usr/include\")\n" > cmake/FindGLEW.cmake
    - printf "set(GLEW_LIBRARY \"/usr/lib/x86_64-linux-gnu/libGLEW.so\")\n" >> cmake/FindGLEW.cmake
    - printf "set(GLEW_FOUND TRUE)\n" >> cmake/FindGLEW.cmake
    - mkdir -p build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-std=c++11 -msse4.1"
    - make -j5
    - sudo make install
