language: cpp
compiler:
    - gcc
    - clang
os:
    - linux
    - osx

before_install:
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update -qq; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install -qq g++-4.8 cmake libxi-dev libxmu-dev freeglut3-dev; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then wget http://launchpadlibrarian.net/160737168/libicu52_52.1-3_amd64.deb; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then wget http://launchpadlibrarian.net/161405671/libglew1.10_1.10.0-3_amd64.deb; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then wget http://launchpadlibrarian.net/161405670/libglew-dev_1.10.0-3_amd64.deb; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then wget http://launchpadlibrarian.net/160798967/libboost1.54-dev_1.54.0-4ubuntu3_amd64.deb; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then wget http://launchpadlibrarian.net/160799003/libboost-system1.54.0_1.54.0-4ubuntu3_amd64.deb; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then wget http://launchpadlibrarian.net/160799004/libboost-system1.54-dev_1.54.0-4ubuntu3_amd64.deb; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then wget http://launchpadlibrarian.net/160798971/libboost-chrono1.54.0_1.54.0-4ubuntu3_amd64.deb; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then wget http://launchpadlibrarian.net/160798972/libboost-chrono1.54-dev_1.54.0-4ubuntu3_amd64.deb; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then wget http://launchpadlibrarian.net/160798999/libboost-serialization1.54.0_1.54.0-4ubuntu3_amd64.deb; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then wget http://launchpadlibrarian.net/160799000/libboost-serialization1.54-dev_1.54.0-4ubuntu3_amd64.deb; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then wget http://launchpadlibrarian.net/160798976/libboost-date-time1.54.0_1.54.0-4ubuntu3_amd64.deb; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then wget http://launchpadlibrarian.net/160798977/libboost-date-time1.54-dev_1.54.0-4ubuntu3_amd64.deb; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then wget http://launchpadlibrarian.net/160798969/libboost-atomic1.54.0_1.54.0-4ubuntu3_amd64.deb; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then wget http://launchpadlibrarian.net/160798970/libboost-atomic1.54-dev_1.54.0-4ubuntu3_amd64.deb; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then wget http://launchpadlibrarian.net/160798979/libboost-filesystem1.54.0_1.54.0-4ubuntu3_amd64.deb; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then wget http://launchpadlibrarian.net/160798980/libboost-filesystem1.54-dev_1.54.0-4ubuntu3_amd64.deb; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then wget http://launchpadlibrarian.net/160798997/libboost-regex1.54.0_1.54.0-4ubuntu3_amd64.deb; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then wget http://launchpadlibrarian.net/160798998/libboost-regex1.54-dev_1.54.0-4ubuntu3_amd64.deb; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then wget http://launchpadlibrarian.net/160798983/libboost-iostreams1.54.0_1.54.0-4ubuntu3_amd64.deb; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then wget http://launchpadlibrarian.net/160798984/libboost-iostreams1.54-dev_1.54.0-4ubuntu3_amd64.deb; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then wget http://launchpadlibrarian.net/160799007/libboost-thread1.54.0_1.54.0-4ubuntu3_amd64.deb; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then wget http://launchpadlibrarian.net/160799008/libboost-thread1.54-dev_1.54.0-4ubuntu3_amd64.deb; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo dpkg -i libglew1.10_1.10.0-3_amd64.deb; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo dpkg -i libglew-dev_1.10.0-3_amd64.deb; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo dpkg -i libicu52_52.1-3_amd64.deb; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo dpkg -i libboost1.54-dev_1.54.0-4ubuntu3_amd64.deb; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo dpkg -i libboost-system1.54.0_1.54.0-4ubuntu3_amd64.deb; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo dpkg -i libboost-system1.54-dev_1.54.0-4ubuntu3_amd64.deb; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo dpkg -i libboost-chrono1.54.0_1.54.0-4ubuntu3_amd64.deb; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo dpkg -i libboost-chrono1.54-dev_1.54.0-4ubuntu3_amd64.deb; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo dpkg -i libboost-serialization1.54.0_1.54.0-4ubuntu3_amd64.deb; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo dpkg -i libboost-serialization1.54-dev_1.54.0-4ubuntu3_amd64.deb; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo dpkg -i libboost-date-time1.54.0_1.54.0-4ubuntu3_amd64.deb; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo dpkg -i libboost-date-time1.54-dev_1.54.0-4ubuntu3_amd64.deb; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo dpkg -i libboost-atomic1.54.0_1.54.0-4ubuntu3_amd64.deb; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo dpkg -i libboost-atomic1.54-dev_1.54.0-4ubuntu3_amd64.deb; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo dpkg -i libboost-filesystem1.54.0_1.54.0-4ubuntu3_amd64.deb; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo dpkg -i libboost-filesystem1.54-dev_1.54.0-4ubuntu3_amd64.deb; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo dpkg -i libboost-regex1.54.0_1.54.0-4ubuntu3_amd64.deb; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo dpkg -i libboost-regex1.54-dev_1.54.0-4ubuntu3_amd64.deb; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo dpkg -i libboost-iostreams1.54.0_1.54.0-4ubuntu3_amd64.deb; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo dpkg -i libboost-iostreams1.54-dev_1.54.0-4ubuntu3_amd64.deb; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo dpkg -i libboost-thread1.54.0_1.54.0-4ubuntu3_amd64.deb; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo dpkg -i libboost-thread1.54-dev_1.54.0-4ubuntu3_amd64.deb; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install glew ;fi
script:
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then printf "set(GLEW_INCLUDE_DIR \"/usr/include\")\n" > cmake/FindGLEW.cmake; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then printf "set(GLEW_LIBRARY \"/usr/lib/x86_64-linux-gnu/libGLEW.so\")\n" >> cmake/FindGLEW.cmake; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then printf "set(GLEW_FOUND TRUE)\n" >> cmake/FindGLEW.cmake; fi
    - mkdir -p build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE:STRING=None -DCMAKE_CXX_FLAGS:STRING="-std=c++11 -msse4.1" -DVSNRAY_ENABLE_EXAMPLES:BOOL=ON
    - make
    - cmake .. -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_CXX_FLAGS:STRING="-std=c++11 -msse4.1" -DVSNRAY_ENABLE_EXAMPLES:BOOL=ON
    - make
    - cmake .. -DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo -DCMAKE_CXX_FLAGS:STRING="-std=c++11 -msse4.1" -DVSNRAY_ENABLE_EXAMPLES:BOOL=ON
    - make
    - cmake .. -DCMAKE_BUILD_TYPE:STRING=MinSizeRel -DCMAKE_CXX_FLAGS:STRING="-std=c++11 -msse4.1" -DVSNRAY_ENABLE_EXAMPLES:BOOL=ON
    - make
    - cmake .. -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_CXX_FLAGS:STRING="-std=c++11 -msse4.1" -DVSNRAY_ENABLE_EXAMPLES:BOOL=ON
    - make
    - sudo make install
