language: cpp
compiler:
    - gcc
    - clang
os:
    - linux
    - osx

env:
    matrix:
        - COMPILER="g++-4.8" STD="CPP11" BUILD_TYPE="None"
        - COMPILER="g++-4.8" STD="CPP11" BUILD_TYPE="Debug"
        - COMPILER="g++-4.8" STD="CPP11" BUILD_TYPE="RelWithDebInfo"
        - COMPILER="g++-4.8" STD="CPP11" BUILD_TYPE="Release"
        - COMPILER="g++-4.8" STD="CPP11" BUILD_TYPE="MinSizeRel"
        - COMPILER="g++-4.8" STD="CPP14" BUILD_TYPE="None"
        - COMPILER="g++-4.8" STD="CPP14" BUILD_TYPE="Debug"
        - COMPILER="g++-4.8" STD="CPP14" BUILD_TYPE="RelWithDebInfo"
        - COMPILER="g++-4.8" STD="CPP14" BUILD_TYPE="Release"
        - COMPILER="g++-4.8" STD="CPP14" BUILD_TYPE="MinSizeRel"

addons:
    apt: 
        sources:
            - boost-latest
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.8
            - libboost1.55-all-dev
            - libxi-dev
            - libxmu-dev
            - freeglut3-dev


before_install:
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install glew ;fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then wget http://launchpadlibrarian.net/161405671/libglew1.10_1.10.0-3_amd64.deb; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then wget http://launchpadlibrarian.net/161405670/libglew-dev_1.10.0-3_amd64.deb; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo dpkg -i libglew1.10_1.10.0-3_amd64.deb; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo dpkg -i libglew-dev_1.10.0-3_amd64.deb; fi
script:
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then printf "set(GLEW_INCLUDE_DIR \"/usr/include\")\n" > cmake/FindGLEW.cmake; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then printf "set(GLEW_LIBRARY \"/usr/lib/x86_64-linux-gnu/libGLEW.so\")\n" >> cmake/FindGLEW.cmake; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then printf "set(GLEW_FOUND TRUE)\n" >> cmake/FindGLEW.cmake; fi

    - export COMPILER_FLAGS="-msse4.1"
    - if [ "$STD" = "CPP11" ]; then export COMPILER_FLAGS="${COMPILER_FLAGS} -std=c++11"; fi
    - if [ "$STD" = "CPP14" ]; then export COMPILER_FLAGS="${COMPILER_FLAGS} -std=c++1y"; fi
    - echo ${COMPILER_FLAGS}

    - mkdir -p build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DCMAKE_CXX_COMPILER=${COMPILER} "-DCMAKE_CXX_FLAGS=${COMPILER_FLAGS}" -DVSNRAY_ENABLE_EXAMPLES=ON
    - make VERBOSE=1
    - sudo make install
